In [51]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,  LabelEncoder
import pickle

In [52]:
data = pd.read_csv('Churn_Modelling.csv')

In [53]:
data.head()
data.shape

(10000, 14)

In [54]:
data = data.drop(['RowNumber', 'CustomerId'	, 'Surname'], axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [55]:
label_encode_gender = LabelEncoder()
data['Gender'] = label_encode_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [56]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder = OneHotEncoder()
geo_encoder= one_hot_encoder.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [57]:
one_hot_encoder.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [58]:
onehot_encoder_geo = pd.DataFrame(geo_encoder.toarray(), columns=['Geography_France', 'Geography_Germany', 'Geography_Spain'])
onehot_encoder_geo

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [59]:
data = pd.concat([data.drop('Geography', axis=1), onehot_encoder_geo],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [60]:
# Save the encode and scaler
with open('label_encode_gender.pkl', 'wb') as file:
    pickle.dump(label_encode_gender, file)
with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(one_hot_encoder, file)  # save the encoder, not the DataFrame

In [61]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [62]:
#Divide thae datset into depedn and in
X = data.drop('Exited', axis=1)
y = data['Exited']

In [63]:
X_tarin, X_test, y_tarin, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_tarin = scaler.fit_transform(X_tarin)
X_test = scaler.transform(X_test)

# y_tarin and y_test are labels and should not be scaled with the feature scaler

In [64]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [65]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [66]:
#Build our ANN Model
model = Sequential(
    [
        Dense(64, activation='relu', input_shape= (X_tarin.shape[1],)),
        Dense(32, activation='relu'),
        Dense(1, activation='sigmoid')
    ]
)

/Users/dayanandahp/Documents/ANN Clasification/myenv/lib/python3.13/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [67]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [68]:
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate = 0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy()
loss

In [69]:
#compile the model
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=['accuracy'])

In [70]:
#set up the Tensorboard
log_dir = "log/fit" + datetime.datetime.now().strftime("%Y%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [71]:
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10
, restore_best_weights=True)

In [72]:
#Train the model
history = model.fit(
    X_tarin, y_tarin, validation_data = (X_test, y_test), epochs = 100, 
    callbacks = [tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8033 - loss: 0.4458 - val_accuracy: 0.8355 - val_loss: 0.3856
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/step - accuracy: 0.8475 - loss: 0.3763 - val_accuracy: 0.8590 - val_loss: 0.3589
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 606us/step - accuracy: 0.8577 - loss: 0.3527 - val_accuracy: 0.8600 - val_loss: 0.3498
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 634us/step - accuracy: 0.8569 - loss: 0.3441 - val_accuracy: 0.8580 - val_loss: 0.3466
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 628us/step - accuracy: 0.8605 - loss: 0.3406 - val_accuracy: 0.8645 - val_loss: 0.3430
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 619us/step - accuracy: 0.8605 - loss: 0.3361 - val_accuracy: 0.8550 - val_loss: 0.3475
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 604us/step - accuracy: 0.8618 - loss: 0.3334 - val_accuracy: 0.8605 - val_loss: 0.3459
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - accuracy: 0.8654 - loss: 0.3306 - val_accuracy: 0.8565 - val_loss: 0.3463
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 607us/step - accuracy: 0.8648 - loss: 0.3295 - val_accuracy: 0.8605 - val_loss: 0.3424
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - accuracy: 0.8661 - loss: 0.3258 - val_accuracy: 0.8605 - val_loss: 0.3442
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 634us/step - accuracy: 0.8676 - loss: 0.3236 - val_accuracy: 0.8645 - val_loss: 0.3433
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 607us/step - accuracy: 0.8671 - loss: 0.3217 - val_accuracy: 0.8550 - val_loss: 0.3446
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 620us/step - accuracy: 0.8649 - loss: 0.3200 - val_accuracy: 0.8600 - val_loss: 0.3442
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 599us/step - accuracy: 0.8680 - loss: 0.3177 - val_accuracy: 0.8535 - val_loss: 0.3472
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 600us/step - accuracy: 0.8709 - loss: 0.3164 - val_accuracy: 0.8550 - val_loss: 0.3454
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - accuracy: 0.8681 - loss: 0.3149 - val_accuracy: 0.8585 - val_loss: 0.3417
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - accuracy: 0.8699 - loss: 0.3130 - val_accuracy: 0.8595 - val_loss: 0.3432
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 641us/step - accuracy: 0.8699 - loss: 0.3130 - val_accuracy: 0.8590 - val_loss: 0.3422
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 761us/step - accuracy: 0.8716 - loss: 0.3094 - val_accuracy: 0.8570 - val_loss: 0.3493
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 614us/step - accuracy: 0.8721 - loss: 0.3086 - val_accuracy: 0.8580 - val_loss: 0.3460
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 608us/step - accuracy: 0.8733 - loss: 0.3076 - val_accuracy: 0.8565 - val_loss: 0.3453
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 619us/step - accuracy: 0.8696 - loss: 0.3048 - val_accuracy: 0.8535 - val_loss: 0.3551
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 619us/step - accuracy: 0.8759 - loss: 0.3046 - val_accuracy: 0.8530 - val_loss: 0.3423
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 615us/step - accuracy: 0.8736 - loss: 0.3019 - val_accuracy: 0.8520 - val_loss: 0.3501
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 612us/step - accuracy: 0.8740 - loss: 0.3015 - val_accuracy: 0.8620 - val_loss: 0.3425
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 607us/step - accuracy: 0.8758 - loss: 0.2992 - val_accuracy: 0.8545 - val_loss: 0.3483

In [73]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [74]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [75]:
%tensorboard --logdir log/fit202620260329-181629

Reusing TensorBoard on port 6007 (pid 10137), started 1 day, 0:15:19 ago. (Use '!kill 10137' to kill it.)