In [106]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , LabelEncoder, OneHotEncoder
import pickle

In [107]:
data = pd.read_csv('Churn_Modelling.csv')

In [108]:
data = data.drop(["RowNumber", "CustomerId", "Surname"], axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [109]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [110]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [111]:
data.tail()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [112]:
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded  = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [113]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [114]:
data.columns

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')

In [115]:
data = pd.concat([data.drop("Geography", axis=1), geo_encoded_df], axis=1)

In [116]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [117]:
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [118]:
X_train,X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [119]:
data.tail()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [120]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [121]:
with open('reg_label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender, file)
with open('reg_onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo, file)
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

__ANN Regression__

In [122]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [123]:
model = Sequential([
    Dense(64, activation="relu", input_shape = (X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)
])

model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

/Users/dayanandahp/Documents/ANN Clasification/myenv/lib/python3.13/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [124]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

__Training the Model__

In [125]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [126]:
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [127]:
history = model.fit(
    X_train, y_train,
    validation_data = (X_test, y_test),
    epochs = 100, 
    callbacks = [early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 100375.6406 - mae: 100375.6406 - val_loss: 98510.5078 - val_mae: 98510.5078
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 659us/step - loss: 99604.2812 - mae: 99604.2812 - val_loss: 96966.3516 - val_mae: 96966.3516
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 691us/step - loss: 96907.4609 - mae: 96907.4609 - val_loss: 93024.3672 - val_mae: 93024.3672
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 679us/step - loss: 91630.2578 - mae: 91630.2578 - val_loss: 86480.3750 - val_mae: 86480.3750
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 684us/step - loss: 83960.5781 - mae: 83960.5781 - val_loss: 78084.6875 - val_mae: 78084.6875
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 688us/step - loss: 74955.0469 - mae: 74955.0469 - val_loss: 69302.0859 - val_mae: 69302.0859
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 720us/step - loss: 66233.7109 - mae: 66233.7109 - val_loss: 61740.5430 - val_mae: 61740.5430
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 712us/step - loss: 59253.0664 - mae: 59253.0664 - val_loss: 56313.5352 - val_mae: 56313.5352
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 719us/step - loss: 54740.1523 - mae: 54740.1523 - val_loss: 53168.0352 - val_mae: 53168.0352
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 649us/step - loss: 52256.2656 - mae: 52256.2656 - val_loss: 51723.5352 - val_mae: 51723.5352
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 652us/step - loss: 51065.0430 - mae: 51065.0430 - val_loss: 51133.9492 - val_mae: 51133.9492
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 628us/step - loss: 50553.1992 - mae: 50553.1992 - val_loss: 50912.6797 - val_mae: 50912.6797
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 728us/step - loss: 50323.2070 - mae: 50323.2070 - val_loss: 50791.9375 - val_mae: 50791.9375
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - loss: 50189.3438 - mae: 50189.3438 - val_loss: 50741.1289 - val_mae: 50741.1289
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 652us/step - loss: 50111.8008 - mae: 50111.8008 - val_loss: 50698.1172 - val_mae: 50698.1172
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 597us/step - loss: 50053.6094 - mae: 50053.6094 - val_loss: 50661.8555 - val_mae: 50661.8555
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 600us/step - loss: 50005.0859 - mae: 50005.0859 - val_loss: 50636.7422 - val_mae: 50636.7422
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 605us/step - loss: 49967.0586 - mae: 49967.0586 - val_loss: 50604.5703 - val_mae: 50604.5703
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 608us/step - loss: 49933.5117 - mae: 49933.5117 - val_loss: 50592.7148 - val_mae: 50592.7148
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 608us/step - loss: 49903.9336 - mae: 49903.9336 - val_loss: 50575.4648 - val_mae: 50575.4648
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 599us/step - loss: 49878.1289 - mae: 49878.1289 - val_loss: 50561.1719 - val_mae: 50561.1719
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 598us/step - loss: 49848.4883 - mae: 49848.4883 - val_loss: 50541.5547 - val_mae: 50541.5547
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 597us/step - loss: 49825.8320 - mae: 49825.8320 - val_loss: 50526.1406 - val_mae: 50526.1406
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 597us/step - loss: 49800.5547 - mae: 49800.5547 - val_loss: 50519.3594 - val_mae: 50519.3594
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 593us/step - loss: 49781.1680 - mae: 49781.1680 - val_loss: 50512.9453 - val_mae: 50512.9453
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 599us/step - loss: 49762.5703 - mae: 49762.5703 - val_loss: 50502.1602 - val_mae: 50502.1602
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 595us/step - loss: 49738.7344 - mae: 49738.7344 - val_loss: 50498.3789 - val_mae: 50498.3789
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 596us/step - loss: 49720.8047 - mae: 49720.8047 - val_loss: 50487.8555 - val_mae: 50487.8555
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 597us/step - loss: 49701.1562 - mae: 49701.1562 - val_loss: 50484.8750 - val_mae: 50484.8750
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 607us/step - loss: 49684.2148 - mae: 49684.2148 - val_loss: 50477.8555 - val_mae: 50477.8555
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 593us/step - loss: 49667.2344 - mae: 49667.2344 - val_loss: 50463.9688 - val_mae: 50463.9688
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 599us/step - loss: 49653.4961 - mae: 49653.4961 - val_loss: 50460.5977 - val_mae: 50460.5977
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 607us/step - loss: 49637.9883 - mae: 49637.9883 - val_loss: 50453.8164 - val_mae: 50453.8164
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 600us/step - loss: 49624.7539 - mae: 49624.7539 - val_loss: 50449.9570 - val_mae: 50449.9570
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 590us/step - loss: 49608.5508 - mae: 49608.5508 - val_loss: 50439.6992 - val_mae: 50439.6992
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 603us/step - loss: 49601.9258 - mae: 49601.9258 - val_loss: 50435.9766 - val_mae: 50435.9766
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 597us/step - loss: 49587.9609 - mae: 49587.9609 - val_loss: 50434.1992 - val_mae: 50434.1992
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 598us/step - loss: 49574.8633 - mae: 49574.8633 - val_loss: 50420.3750 - val_mae: 50420.3750
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 598us/step - loss: 49564.6055 - mae: 49564.6055 - val_loss: 50423.9961 - val_mae: 50423.9961
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 632us/step - loss: 49555.5000 - mae: 49555.5000 - val_loss: 50423.6914 - val_mae: 50423.6914
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 595us/step - loss: 49548.8828 - mae: 49548.8828 - val_loss: 50419.6445 - val_mae: 50419.6445
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 592us/step - loss: 49539.7695 - mae: 49539.7695 - val_loss: 50408.9492 - val_mae: 50408.9492
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 598us/step - loss: 49528.2344 - mae: 49528.2344 - val_loss: 50411.4219 - val_mae: 50411.4219
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 632us/step - loss: 49519.7578 - mae: 49519.7578 - val_loss: 50403.3984 - val_mae: 50403.3984
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 601us/step - loss: 49510.0977 - mae: 49510.0977 - val_loss: 50395.2188 - val_mae: 50395.2188
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 601us/step - loss: 49501.6172 - mae: 49501.6172 - val_loss: 50402.6875 - val_mae: 50402.6875
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 587us/step - loss: 49493.4453 - mae: 49493.4453 - val_loss: 50396.3438 - val_mae: 50396.3438
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 602us/step - loss: 49489.6016 - mae: 49489.6016 - val_loss: 50401.9102 - val_mae: 50401.9102
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 593us/step - loss: 49478.3320 - mae: 49478.3320 - val_loss: 50407.1016 - val_mae: 50407.1016
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 595us/step - loss: 49472.4023 - mae: 49472.4023 - val_loss: 50407.0273 - val_mae: 50407.0273
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 589us/step - loss: 49465.1836 - mae: 49465.1836 - val_loss: 50417.9844 - val_mae: 50417.9844
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 597us/step - loss: 49459.6523 - mae: 49459.6523 - val_loss: 50417.7344 - val_mae: 50417.7344
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 592us/step - loss: 49453.1953 - mae: 49453.1953 - val_loss: 50412.8359 - val_mae: 50412.8359
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 588us/step - loss: 49447.2656 - mae: 49447.2656 - val_loss: 50400.7656 - val_mae: 50400.7656
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 611us/step - loss: 49442.5391 - mae: 49442.5391 - val_loss: 50403.1328 - val_mae: 50403.1328

__Evaluate The Model__

In [128]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [129]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6008 (pid 41316), started 0:48:52 ago. (Use '!kill 41316' to kill it.)

In [130]:
test_loss, test_mae = model.evaluate(X_test,y_test)
print(f"Test MAE: {test_mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 512us/step - loss: 50395.2188 - mae: 50395.2188
Test MAE: 50395.21875

In [131]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.